Added profile features
HackIllinois/iOS pull request #369
Opened 2021-03-11 02:44 UTC by hsahn0323

Added the current user profile features, including time zone, point system, and skillsets.

2021-03-12 08:17 UTC, PatrickKan requested changes

2021-03-12 08:17 UTC, PatrickKan commented on HackIllinois/FlowControllers/HILoginFlowController.swift
> +                var profile = profile
how is this generated?

2021-03-12 08:17 UTC, PatrickKan commented on HackIllinois/FlowControllers/HILoginFlowController.swift
> +                var profile = profile
Do you know if it works with a real profile?

2021-03-12 08:22 UTC, PatrickKan commented
Did you test if it works with a real profile, or can you ping heesoo to generate a real profile for you to test with?

2021-03-13 09:20 UTC, jeffkim2001 approved these changes

2021-03-13 09:21 UTC, merged