QR Scanner
HackIllinois/iOS pull request #412
Opened 2022-01-14 01:34 UTC by ifisq

## Description

Fixes #135 

- Adds QR scanner functionality to app.

## Todos

## Screenshots

I don't have a screenshot of this working since we don't have any usable QR codes yet. The only added page is a camera for the QR scanner.

2022-01-14 04:46 UTC, ashayp22 requested changes
QR Scanner works perfectly, great work Aryan😄! 

I left some inline comments, but they should be quick to fix. 

After you finish up with closing the QR scanner after scanning a code, I can take a look at any new code and then you can merge ✅

2022-01-14 04:46 UTC, ashayp22 commented on HIAPI/Models/Event.swift
> +    public let userId: String
No longer a need for this since staff won't be scanning. Can be deleted ❌

2022-01-14 04:46 UTC, ashayp22 commented on HIAPI/Services/EventService.swift
> +    public static func track(eventId: String, userId: String) ->APIRequest<EventTrack> {
Same as above, can be deleted

2022-01-14 04:46 UTC, ashayp22 commented on HackIllinois/FlowControllers/HITabBarController.swift
> +            let notEnabledAlert = UIAlertController(title: "This feature hasn't been enabled yet!", message: "", preferredStyle: .alert)
Maybe change the text to "You need to log out of your current account and log in as an attendee to check in to events."

2022-01-14 04:46 UTC, ashayp22 commented on HackIllinois/ViewControllers/HIScanQRCodeViewController.swift
> +        closeButton.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 3).isActive = true
Could you make the closeButton a bit larger and farther from the edge so it is easer to tap?

2022-01-16 00:59 UTC, ifisq commented
@ashayp22 I've implemented your requested changes. I also updated the branch to the latest version of dev to resolve a merge conflict. Just wanted to let you know that for some reason, the latest version of dev isn't building on my MacBook properly, and I'm getting an error that it isn't able to load one of the assets you added. Here's a screenshot:
![image](https://user-images.githubusercontent.com/35982379/149643240-631548fa-c9b3-4e2d-8486-cb6572f7d658.png)

2022-01-16 17:03 UTC, ashayp22 commented
> @ashayp22 I've implemented your requested changes. I also updated the branch to the latest version of dev to resolve a merge conflict. Just wanted to let you know that for some reason, the latest version of dev isn't building on my MacBook properly, and I'm getting an error that it isn't able to load one of the assets you added. Here's a screenshot: ![image](https://user-images.githubusercontent.com/35982379/149643240-631548fa-c9b3-4e2d-8486-cb6572f7d658.png)

I deleted the Matching asset since we no longer will be using it. You can replace that line with:
`tabBarItem = UITabBarItem(title: "", image: #imageLiteral(resourceName: "leaderboard"), selectedImage: #imageLiteral(resourceName: "LeaderboardSelected"))`

2022-01-16 18:56 UTC, ashayp22 submitted a review, later dismissed
One more tiny change: can you make the color of the `closeButton` black? 

After that, feel free to go ahead and merge!

------------------------

Update: Sorry, one more thing: I noticed that if the user
1. Goes to the Profile page
2. Clicks the QR Scanner button and scans a QR code
3. Returns back to the Profile page after the QR scanner is closed.

The points aren't updated on the Profile Page. 

I think this is because `reloadProfile()` function in HIProfileViewController isn't called after the QR scanner is closed. Can you think of a way to call that function after the user successfully scans a QR code?

2022-01-16 22:09 UTC, ifisq commented
@ashayp22 i've added the requested changes, let me know if there's anything else i need to do before merging.

2022-01-17 00:23 UTC, ashayp22 approved these changes
Looks good, you can merge

2022-01-20 02:37 UTC, merged