Fix attendee login and refactor profile model
HackIllinois/iOS pull request #548
Opened 2023-11-23 20:15 UTC by s0phialiu

## Description

* Allows attendees to login by restructuring login flow to not rely on pulling user information from registration data.
* Refactored profile model by changing the following fields: discord to discordTag, id to userId, and first/last name to displayName. 
* Attendees can now login and view their profile.
<img width="323" alt="Screen Shot 2023-11-23 at 2 14 37 PM" src="https://github.com/HackIllinois/iOS/assets/91706701/cf522633-60cb-400a-a0bd-c37c854a0179">

2023-11-23 20:16 UTC, s0phialiu commented
Commented out foodWave for now since I believe it is getting sent to us another way.

2023-12-03 18:01 UTC, lasyaneti commented on HackIllinois/FlowControllers/HILoginFlowController.swift
> +                        NotificationCenter.default.post(name: .loginUser, object: nil, userInfo: ["user": user])
Logout dispatch queue might need changes too?

2023-12-03 18:02 UTC, lasyaneti requested changes
This breaks logout functionality

2023-12-03 18:58 UTC, lasyaneti approved these changes

2023-12-03 18:59 UTC, merged